# Generated by Django 5.1.1 on 2024-09-23 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(default='no-image.png', upload_to='technology_pics', verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('description', models.TextField()),
                ('description_es', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('image', models.ImageField(default='default-icon.png', upload_to='profile_pics', verbose_name='Image')),
                ('logo', models.ImageField(default='logo.png', upload_to='extra', verbose_name='Logo')),
                ('mail', models.CharField(max_length=200)),
                ('resume', models.FileField(blank=True, upload_to='resumes')),
                ('linkedin_url', models.CharField(blank=True)),
                ('github_url', models.CharField(blank=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('description_es', models.TextField(blank=True, max_length=500, null=True)),
                ('description_en', models.TextField(blank=True, max_length=500, null=True)),
                ('project_url', models.CharField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Contribution', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('image_preview', models.ImageField(default='no-image.png', upload_to='project_pics', verbose_name='Image Preview')),
                ('github_url', models.CharField(blank=True)),
                ('preview_url', models.CharField(blank=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Project', to='portfolio.profile')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_title_es', models.CharField(max_length=100, null=True)),
                ('job_title_en', models.CharField(max_length=100, null=True)),
                ('job_description', models.TextField(blank=True)),
                ('job_description_es', models.TextField(blank=True, null=True)),
                ('job_description_en', models.TextField(blank=True, null=True)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Experience', to='portfolio.profile')),
                ('technologies', models.ManyToManyField(blank=True, to='portfolio.technology')),
            ],
        ),
    ]
