# Generated by Django 5.1.1 on 2024-09-15 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
