# Generated by Django 5.1.1 on 2024-09-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_profile_github_url_alter_profile_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='image_preview',
            field=models.ImageField(default='default_icon.png', upload_to='experience_pics', verbose_name='Image Preview'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_preview',
            field=models.ImageField(default='default_icon.png', upload_to='project_pics', verbose_name='Image Preview'),
        ),
    ]
