# Generated by Django 5.1.1 on 2024-09-16 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_experience_image_preview_project_image_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='logo',
            field=models.ImageField(default='logo.png', upload_to='extra', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='image_preview',
            field=models.ImageField(default='no-image.png', upload_to='experience_pics', verbose_name='Image Preview'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default-icon.png', upload_to='profile_pics', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_preview',
            field=models.ImageField(default='no-image.png', upload_to='project_pics', verbose_name='Image Preview'),
        ),
    ]
