# Generated by Django 5.1.1 on 2024-09-18 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_contribution'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('logo', models.ImageField(default='no-image.png', upload_to='technology_pics', verbose_name='Logo')),
            ],
        ),
        migrations.RemoveField(
            model_name='experience',
            name='image_preview',
        ),
        migrations.AddField(
            model_name='experience',
            name='company_logo',
            field=models.ImageField(default='no-image.png', upload_to='experience_pics', verbose_name='Company Logo'),
        ),
        migrations.AddField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.technology'),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(to='portfolio.technology'),
        ),
    ]
