# Generated by Django 5.1.1 on 2024-09-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_technology_remove_experience_image_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='job_description',
            field=models.TextField(blank=True),
        ),
    ]
