# Generated by Django 5.1.1 on 2024-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_alter_experience_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_end',
            field=models.DateField(blank=True),
        ),
    ]
