# Generated by Django 5.1.1 on 2024-09-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_alter_experience_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.technology'),
        ),
    ]
