# Generated by Django 5.1.1 on 2024-09-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_experience_date_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, to='portfolio.technology'),
        ),
    ]
