# Generated by Django 5.1.1 on 2024-09-21 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0018_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
    ]
