# Generated by Django 5.1.1 on 2024-09-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0019_alter_experience_date_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_es',
            field=models.TextField(null=True),
        ),
    ]
