# Generated by Django 5.1.1 on 2024-09-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_profile_description_en_profile_description_es'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description_es',
        ),
        migrations.AddField(
            model_name='profile',
            name='description_e',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='description_s',
            field=models.TextField(null=True),
        ),
    ]
