# Generated by Django 5.1.1 on 2024-09-23 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_remove_profile_description_en_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='description_e',
            new_name='description_es',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description_s',
        ),
    ]
